# Nixpacks configuration for Railway deployment
# gcc is required for compiling Python packages with C extensions (numpy, pandas, scikit-learn)
[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --access-logfile - --error-logfile - --log-level info app:app"
